### ISSUE TITLE
chart  ContinuousSeries legend order problem

### ISSUE THREAD

**Issue by beyoung** [wcharczuk/go-chart#57]
First of all ,thanks for this awesome library, it helps a lot for me. 

But a chart legend problem bothers me. demo picture is below
![](http://7xjlcg.com1.z0.glb.clouddn.com/1242470.png)
, i want to change the legend order like this:
* Class HC
* Class 1
* Class 2
* Class 3
* Class 4
but actually  the order is the index order, so how to do it? is there any documents?

**Comment by wcharczuk** [comment]
The legend typically draws in the order you register the series. If you'd like a different order than the series order, we can maybe add a `SortIndex` interface that you would return what relative order you'd like your objects to shown in the chart, but otherwise it's been sufficient to use the chart series order.
